-- Seed Sightings
INSERT OR IGNORE INTO sightings (id, user_id, type, subcategory, description, severity, latitude, longitude, address, image_key, bleach_percent, water_temp, depth, mission_id, validated, validation_count, status, created_at, ai_analysis) VALUES
(1, 'user_player1', 'garbage', 'plastic_bottle', 'Found a pile of plastic bottles near the shore.', 3, 34.0094, -118.4973, 'Santa Monica Beach', 'sightings/bottle.jpg', NULL, NULL, NULL, 1, 1, 5, 'approved', datetime('now', '-2 days'), '{"confidence": 0.95, "label": "plastic"}'),
(2, 'user_scientist', 'coral', 'branching', 'Healthy branching coral observed.', 1, -18.2871, 147.6992, 'Great Barrier Reef', 'sightings/coral_healthy.jpg', 0, 26.5, 10.5, 2, 1, 10, 'approved', datetime('now', '-5 days'), '{"bleachPercent": 0, "confidence": 0.98}'),
(3, 'user_ambassador', 'wildlife', 'turtle', 'Green sea turtle spotted feeding.', 1, -8.7185, 115.1686, 'Kuta Beach', 'sightings/turtle.jpg', NULL, NULL, NULL, 3, 1, 25, 'approved', datetime('now', '-10 days'), NULL),
(4, 'user_player2', 'garbage', 'fishing_net', 'Ghost net entangled on rocks.', 5, 25.7617, -80.1918, 'Miami Beach', 'sightings/net.jpg', NULL, NULL, 5.0, 4, 1, 2, 'flagged', datetime('now', '-1 days'), NULL),
(5, 'user_player3', 'floating', 'oil_sheen', 'Possible oil sheen on water surface.', 4, 34.0150, -118.5000, 'Santa Monica Bay', NULL, NULL, NULL, NULL, NULL, 0, 0, 'pending', datetime('now', '-30 minutes'), NULL),
(6, 'user_scientist', 'coral', 'bleached', 'Severe bleaching event in section B.', 5, -18.2900, 147.7000, 'Great Barrier Reef', 'sightings/bleached.jpg', 85, 29.0, 8.0, 2, 1, 15, 'approved', datetime('now', '-6 days'), '{"bleachPercent": 85, "confidence": 0.92}'),
(7, 'user_player4', 'wildlife', 'dolphin', 'Pod of dolphins spotted surfing!', 1, 21.3069, -157.8583, 'Waikiki Beach', 'sightings/dolphin.jpg', NULL, NULL, NULL, NULL, 1, 12, 'approved', datetime('now', '-12 hours'), NULL),
(8, 'user_player5', 'garbage', 'chemical_drum', 'Found a rusted chemical drum on the rocks.', 5, -33.9249, 18.4241, 'Sea Point, Cape Town', NULL, NULL, NULL, NULL, NULL, 0, 0, 'pending', datetime('now', '-3 hours'), NULL),
(9, 'user_player6', 'floating', 'seaweed_overgrowth', 'High concentration of sargassum noticed.', 2, 43.2965, 5.3698, 'Marseille Harbor', NULL, NULL, NULL, NULL, NULL, 1, 3, 'approved', datetime('now', '-3 days'), NULL),
(10, 'user_scientist2', 'coral', 'brain_coral', 'Excellent specimen of brain coral found.', 1, 60.3913, 5.3221, 'Bergen Reef', 'sightings/brain_coral.jpg', 0, 12.0, 15.0, NULL, 1, 20, 'approved', datetime('now', '-15 days'), '{"bleachPercent": 0, "confidence": 0.99}'),
(11, 'user_player8', 'wildlife', 'manta_ray', 'Gigantic manta ray gliding through the bay.', 1, -17.7134, 178.0650, 'Viti Levu', NULL, NULL, NULL, NULL, NULL, 1, 40, 'approved', datetime('now', '-4 days'), NULL),
(12, 'user_player9', 'garbage', 'microplastics', 'Heavy microplastics found in sand samples.', 4, 21.1619, -86.8515, 'Cancun Beach', NULL, NULL, NULL, NULL, NULL, 0, 1, 'pending', datetime('now', '-1 hour'), NULL);
